"use client";

import * as React from "react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import {
    Dialog,
    DialogTrigger,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogDescription,
    DialogFooter,
    DialogClose,
} from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";

export function TermsDialog({
    onConfirm,
    disabled,
}: {
    onConfirm: () => void;
    disabled?: boolean;
}) {
    const [open, setOpen] = React.useState(false);
    const [atEnd, setAtEnd] = React.useState(false);
    const [checked, setChecked] = React.useState(false);

    const handleOpenChange = (v: boolean) => {
        setOpen(v);
        if (!v) {
            setAtEnd(false);
            setChecked(false);
        }
    };

    const onScrollEnd = (e: React.UIEvent<HTMLDivElement>) => {
        const el = e.currentTarget;
        const reached = el.scrollTop + el.clientHeight >= el.scrollHeight - 4;
        if (reached) setAtEnd(true);
    };

    const canAgree = atEnd && checked;

    return (
        <Dialog open={open} onOpenChange={handleOpenChange}>
            <DialogTrigger asChild>
                <Button disabled={disabled}>Checkout</Button>
            </DialogTrigger>

            <DialogContent className="sm:max-w-xl">
                <DialogHeader>
                    <DialogTitle>Terms and Agreement (Full Legal and Philosophical Version)</DialogTitle>
                    <DialogDescription>
                        You are required to read all of the following to continue.
                        Please do not blink.
                    </DialogDescription>
                </DialogHeader>

                <ScrollArea
                    className="h-[30rem] border rounded-md p-4 bg-muted/20 text-sm leading-relaxed space-y-4"
                    onScrollCapture={onScrollEnd}
                >
                    <p>
                        Welcome to the Infinite Terms Experience™. By engaging with this section, you
                        agree that your patience will be tested to its limits and that any frustration
                        you experience is entirely your own responsibility. Your scrolling behavior may
                        be analyzed for future amusement.
                    </p>
                    <br />

                    <p>
                        Section 1: Purpose. These Terms exist solely to delay your checkout process and
                        to simulate the bureaucratic beauty of online compliance systems. They are not
                        intended to protect you, the user, but rather to provide a false sense of legal
                        formality.
                    </p>
                    <br />

                    <p>
                        Section 2: Definitions. "Website" refers to the current tab that you are
                        regretting opening. "Cart" means the emotional baggage you carry alongside your
                        shopping items. "User" means you, the individual questioning life choices while
                        reading this paragraph.
                    </p>
                    <br />

                    <p>
                        Section 3: User Obligations. You are required to read these terms in a single
                        sitting without snacks or distractions. You may not skim, glance, or
                        scroll-speed-read. Violations will result in mild guilt.
                    </p>
                    <br />

                    <p>
                        Section 4: Agreement Duration. This Agreement remains in effect until you stop
                        thinking about it, which may take years.
                    </p>
                    <br />

                    <p>
                        Section 5: Data Handling. We collect your clicks, scroll velocity, caffeine
                        level, typing rhythm, and ambient lighting conditions to improve absolutely
                        nothing.
                    </p>
                    <br />

                    <p>
                        Section 6: AI Interaction. You agree that all responses generated by AI are to
                        be taken as both deeply meaningful and entirely meaningless at the same time.
                        This paradox will not be explained.
                    </p>
                    <br />

                    <p>
                        Section 7: Warranty Disclaimer. The sneakers, and indeed all physical objects,
                        exist “as is.” No warranty is provided for existential fulfillment or coolness
                        upon wearing.
                    </p>
                    <br />

                    <p>
                        Section 8: Delivery Expectations. Delivery dates are ceremonial. Your order may
                        arrive yesterday, next century, or as a dream sequence in a future life.
                    </p>
                    <br />

                    <p>
                        Section 9: Intellectual Property. These terms are protected under the “Nobody
                        Will Ever Read This” license. Unauthorized reading is ironically authorized.
                    </p>
                    <br />

                    <p>
                        Section 10: Customer Conduct. You agree to maintain eye contact with your
                        screen while scrolling and to sigh audibly every 30 seconds.
                    </p>
                    <br />

                    <p>
                        Section 11: Sleep Policy. Falling asleep during this process counts as implied
                        consent.
                    </p>
                    <br />

                    <p>
                        Section 12: Return Procedure. To initiate a return, contact customer service,
                        who will forward you to a bot, which will forward you to another bot, which will
                        forward you to enlightenment.
                    </p>
                    <br />

                    <p>
                        Section 13: Corporate Values. We believe in transparency, as long as it is
                        opaque enough to confuse you.
                    </p>
                    <br />

                    <p>
                        Section 14: Sustainability Clause. Each scroll down represents one leaf falling
                        from a virtual tree. Please scroll responsibly.
                    </p>
                    <br />

                    <p>
                        Section 15: Limitation of Liability. We are not liable for eye strain, lost
                        time, or the psychological impact of this absurd document.
                    </p>
                    <br />

                    <p>
                        Section 16: Multiverse Clause. In at least one alternate universe, you have
                        already agreed to these terms.
                    </p>
                    <br />

                    <p>
                        Section 17: Customer Service Response Time. Between 2 - 6 business millennia.
                    </p>
                    <br />

                    <p>
                        Section 18: Cookie Policy. All cookies are digital, gluten-free, and entirely
                        non-existent.
                    </p>
                    <br />

                    <p>
                        Section 19: Security Notice. Our site uses 128-bit encryption, 256-bit
                        confusion, and 512-bit apathy to protect your data.
                    </p>
                    <br />

                    <p>
                        Section 20: Refund Process. Refunds will be granted exclusively in
                        cryptocurrency that no longer exists.
                    </p>
                    <br />

                    <p>
                        Section 21: Loyalty Program. The longer you scroll, the higher your loyalty
                        level. Rewards include deep regret and bragging rights.
                    </p>
                    <br />

                    <p>
                        Section 22: Fine Print. If you are reading this, congratulations—you have
                        reached the fine print. The fine print may contain smaller fine print. Please
                        zoom in responsibly.
                    </p>
                    <br />

                    <p>
                        Section 23: Self-Awareness Clause. You acknowledge that this entire section is
                        self-aware and judging you silently.
                    </p>
                    <br />

                    <p>
                        Section 24: Inflation Adjustment. Prices, terms, and patience levels may inflate
                        without warning.
                    </p>
                    <br />

                    <p>
                        Section 25: Legal Jurisdiction. All disputes will be resolved via online
                        rock-paper-scissors, best of seven.
                    </p>
                    <br />

                    <p>
                        Section 26: Scroll Responsibility. The system will only recognize your agreement
                        after you have scrolled far enough to question your sanity.
                    </p>
                    <br />

                    <p>
                        Section 27: Loyalty Reaffirmation. Users must nod once every five paragraphs to
                        indicate comprehension.
                    </p>
                    <br />

                    <p>
                        Section 28: Ethical Disclosure. No interns were paid in the making of this text.
                    </p>
                    <br />

                    <p>
                        Section 29: AI Co-Authorship. Portions of this agreement were written by
                        algorithms trained on bad legal drama scripts.
                    </p>
                    <br />

                    <p>
                        Section 30: Philosophical Clause. If a tree falls in the forest and nobody
                        scrolls to see it, is it still covered under this agreement?
                    </p>
                    <br />

                    <p>
                        Section 31: Footer Inception. The footer of this agreement contains another
                        footer, which also contains a footer. Keep scrolling.
                    </p>
                    <br />

                    <p>
                        Section 32: Appreciation Note. Thank you for your endurance. You are now
                        emotionally prepared to work in compliance departments.
                    </p>
                    <br />

                    <div className="mt-8 flex items-start gap-2 pt-4">
                        <Checkbox
                            id="agree-inner"
                            checked={checked}
                            onCheckedChange={(v) => setChecked(Boolean(v))}
                            disabled={!atEnd}
                        />
                        <Label
                            htmlFor="agree-inner"
                            className={`text-sm ${!atEnd ? "text-muted-foreground" : ""}`}
                        >
                            I have read every paragraph, reflected deeply, and accept my fate.
                        </Label>
                    </div>
                    <br />

                    <p>
                        Section 33: Hidden Continuation. You thought that was the end? Think again.
                        There's always more bureaucracy.
                    </p>
                    <br />

                    <p>
                        Section 34: Terms of Terms. You agree that the existence of terms implies other
                        terms, which are not shown here but are equally binding.
                    </p>
                    <br />

                    <p>
                        Section 35: Post-Agreement Fatigue. Should you experience dizziness, please
                        continue scrolling slowly until acceptance sets in.
                    </p>
                    <br />

                    <p>
                        Section 36: Congratulations. If you are still reading, you have unlocked the
                        hidden achievement “Dedicated Reader (Tier 1).”
                    </p>
                    <br />

                    <p>
                        Section 37: Final Reminder. Clicking “Agree” does not actually close the popup
                        faster. That's by design.
                    </p>
                    <br />

                    <p>
                        Section 38: Thank you for your time. We hope this document has prepared you for
                        a lifetime of digital inconvenience.
                    </p>
                    <br />

                    {[...Array(60)].map((_, i) => (
                        <React.Fragment key={i}>
                            <p>
                                Section {39 + i}: In the continued interest of full disclosure, this paragraph exists solely
                                to create vertical distance between you and the checkbox you're seeking. The content herein
                                serves no legal purpose, emotional comfort, or instructional value. Please keep scrolling to
                                reaffirm your dedication to inefficiency.
                            </p>
                            <br />
                        </React.Fragment>
                    ))}

                </ScrollArea>

                <DialogFooter className="mt-2">
                    <DialogClose asChild>
                        <Button variant="outline">Cancel</Button>
                    </DialogClose>
                    <Button
                        className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                        disabled={!canAgree}
                        onClick={() => {
                            onConfirm();
                            setOpen(false);
                        }}
                    >
                        Agree & Checkout
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
