name: kelompok_8_ethack

services:
  tk_2:
    build: .
    ports:
      - "1337:1337"
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SYS_CHROOT
      - SETGID
      - SETUID
    deploy:
      resources:
        limits:
          memory: 128M